import { Router, type IRouter } from "express";
import healthRouter from "./health";
import membersRouter from "./members";
import eventsRouter from "./events";
import residentMeetingsRouter from "./residentMeetings";
import newsRouter from "./news";
import galleryRouter from "./gallery";
import joinRequestsRouter from "./joinRequests";
import contactRouter from "./contact";
import statsRouter from "./stats";
import authRouter from "./auth";
import visitsRouter from "./visits";
import maintenanceRouter from "./maintenance";
import complaintsRouter from "./complaints";
import emergencyRouter from "./emergency";
import amenitiesRouter from "./amenities";
import societyRouter from "./society";
import buildingsRouter from "./buildings";
import flatsRouter from "./flats";
import expenseCategoriesRouter from "./expenseCategories";
import vendorsRouter from "./vendors";
import maintenanceRatesRouter from "./maintenanceRates";
import maintenanceSettingsRouter from "./maintenanceSettings";
import maintenanceDiscountsRouter from "./maintenanceDiscounts";
import specialContributionsRouter from "./specialContributions";
import vendorBillsRouter from "./vendorBills";
import billPaymentsRouter from "./billPayments";
import maintenanceCollectionsRouter from "./maintenanceCollections";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(membersRouter);
router.use(eventsRouter);
router.use(residentMeetingsRouter);
router.use(newsRouter);
router.use(galleryRouter);
router.use(joinRequestsRouter);
router.use(contactRouter);
router.use(statsRouter);
router.use(authRouter);
router.use(visitsRouter);
router.use(maintenanceRouter);
router.use(complaintsRouter);
router.use(emergencyRouter);
router.use(amenitiesRouter);
router.use(societyRouter);
router.use(buildingsRouter);
router.use(flatsRouter);
router.use(expenseCategoriesRouter);
router.use(vendorsRouter);
router.use(maintenanceRatesRouter);
router.use(maintenanceSettingsRouter);
router.use(maintenanceDiscountsRouter);
router.use(specialContributionsRouter);
router.use(vendorBillsRouter);
router.use(billPaymentsRouter);
router.use(maintenanceCollectionsRouter);
router.use(reportsRouter);

export default router;
